### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by vs-krasnov** [sgjsakura/aspnet5#2]
I want to use your solution in my project, I look for paged list, but don't know what is the first step.
Could you please provide a few examples how to utilize your package?

**Comment by sgjsakura** [comment]
@vs-krasnov You may find the PagedList nuget package at: https://www.nuget.org/packages/Sakura.AspNet.Mvc.PagedList/

The usage for this package can be found in this [Demo](demo.md).

Hope the above information helps. If you have any problem, please feel free to reply or contact me directly.

**Comment by vs-krasnov** [comment]
@sgjsakura Thanks a lot! This is exactly what I need, sorry to bother you!
